"""
llm.py

This module contains the LLM wrapper used to communicate with the local
LLM running through Ollama.

Purpose:
- Centralize the model call logic
- Allow other modules to query the LLM easily
"""

import ollama


def query_llm(prompt, model="llama3"):
    """
    Sends a prompt to the LLM and returns the generated response.

    Parameters:
    prompt (str): The input prompt that will be sent to the LLM.
    model (str): The name of the Ollama model to be used (default: llama3).

    Returns:
    str: The text response generated by the LLM.
    """

    # Send the prompt to the LLM using Ollama chat API
    response = ollama.chat(
        model=model,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    # Extract and return the model's message content
    return response["message"]["content"]